fix: #1005: escale controller status port from being scraped by Prometheus
Kong/charts pull request #1008
Opened 2024-02-15 17:30 UTC by sgrzemski

…erviceMonitor

#### What this PR does / why we need it:

#### Which issue this PR fixes
  - fixes #1005

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] PR is based off the current tip of the `main` branch.
- [X] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [X] New or modified sections of values.yaml are documented in the README.md
- [X] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2024-02-16 18:46 UTC, rainest approved these changes
Dunno if we should bother making the probe configuration that prompted the problem change use the named port rather than its number, but I figure it doesn't matter much. We don't let you configure it and have no intention of changing it away from 10254.

2024-02-16 18:48 UTC, rainest requested changes, later dismissed

2024-02-16 18:48 UTC, rainest commented on charts/kong/templates/_helpers.tpl
> +  - name: controller-status
```suggestion
  - name: cstatus
```

2024-02-16 18:48 UTC, rainest commented on charts/kong/CHANGELOG.md
> +* Escape ingress-controller status port from being scraped by Prometheus and its ServiceMonitor
```suggestion
* Rename the controller status port. This fixes a collision with the proxy status port in the Prometheus ServiceMonitor.
```

2024-02-21 08:56 UTC, czeslavo submitted a review, later dismissed

2024-02-21 08:59 UTC, czeslavo approved these changes, later dismissed

2024-02-21 09:15 UTC, czeslavo approved these changes

2024-02-21 09:19 UTC, merged