Missing load balancer values
Kong/charts pull request #1116
Opened 2024-08-15 21:51 UTC by FedericoAntoniazzi

#### What this PR does / why we need it:
There were missing values in the default values.yaml file, which required visiting the implementation for discovering how to configure the proxy Service.
This PR reports those values in the default values.yaml file.

#### Special notes for your reviewer:

#### Checklist
- [x] PR is based off the current tip of the `main` branch.
- [x] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2024-08-15 21:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=1116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=1116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=1116) it.</sub>

2024-08-15 21:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=1116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=1116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=1116) it.</sub>

2024-08-16 09:02 UTC, pmalek requested changes
You'll probably want to run `make test.golden.update` to update the golden files for tests

2024-08-16 09:02 UTC, pmalek commented on charts/kong/values.yaml
> +  loadBalancerIP: ""
Given that this has been deprecated in 1.24 we probably will not want to add this at this point.

```suggestion
```

2024-08-16 09:02 UTC, pmalek commented on charts/kong/CHANGELOG.md
> +* Add missing load balancer service values
```suggestion

* Add missing load balancer service values
  [#1116](https://github.com/Kong/charts/pull/1116)
```

2024-08-16 09:06 UTC, FedericoAntoniazzi commented on charts/kong/CHANGELOG.md
> +* Add missing load balancer service values
Thanks, I missed that

2024-08-16 16:16 UTC, FedericoAntoniazzi commented
> You'll probably want to run `make test.golden.update` to update the golden files for tests

Hi @pmalek. I ran `make test.golden.update` but there are no changes. everything seems to be okay

2024-10-01 11:59 UTC, pmalek approved these changes, later dismissed
Thanks for the contribution. Please rebase on top of latest changes in `main`.

2024-10-01 15:58 UTC, FedericoAntoniazzi commented
Hi @pmalek, thanks for your review and support!
I rebased the commits on top of `main`.

2024-10-02 08:42 UTC, pmalek approved these changes

2024-10-02 08:42 UTC, merged