[kong] fix env CONTROLLER_ADMISSION_WEBHOOK_LISTEN "0.0.0.0:%!d(float64=8080…
Kong/charts pull request #155
Opened 2020-06-10 02:36 UTC by xiongxiaoxx

…)" error

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes [#154](https://github.com/Kong/charts/issues/154)

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x ] PR is based off the current tip of the `next` branch and targets `next`, not `master`
- [ x] Title of the PR and commit headers start with chart name (e.g. `[kong]`)

2020-06-10 02:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=155) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=155) before we can accept your contribution.<br/><hr/>**peterxiong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=155) it.</sub>

2020-06-10 16:41 UTC, rainest requested changes
Thanks for catching this. Looks good aside from the commit format. Can you reword that to shorten the title and include the longer explanation in the body? I suggest:

```
[kong] fix admission listen type conversion

Fix issue where CONTROLLER_ADMISSION_WEBHOOK_LISTEN would render with a
botched type conversion, e.g. "0.0.0.0:%!d(float64=8080)".
```
With that and the CLA signature you should be all set.

2020-06-11 08:46 UTC, xiongxiaoxx commented
> Thanks for catching this. Looks good aside from the commit format. Can you reword that to shorten the title and include the longer explanation in the body? I suggest:
> 
> ```
> [kong] fix admission listen type conversion
> 
> Fix issue where CONTROLLER_ADMISSION_WEBHOOK_LISTEN would render with a
> botched type conversion, e.g. "0.0.0.0:%!d(float64=8080)".
> ```
> 
> With that and the CLA signature you should be all set.

Thank you for your advice, I've changed commit message

2020-06-12 22:40 UTC, rainest approved these changes

2020-06-12 22:41 UTC, merged