[kong] add support for sidecar containers
Kong/charts pull request #174
Opened 2020-07-23 02:11 UTC by dsem

#### What this PR does / why we need it:

Adds support for arbitrary sidecar containers to the Deployment resource.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `next` branch and targets `next`, not `master`
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Title of the PR and commit headers start with chart name (e.g. `[kong]`)

2020-07-23 02:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=174) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=174) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=174) it.</sub>

2020-07-23 18:01 UTC, rainest requested changes
Sweet! This is a good flexible approach to doing what I currently do with debug branches (see https://github.com/Kong/charts/commit/ce1b95214a18abbfe191c57ce411c2364ff7d4d5 for an example) in a way that's much easier to utilize in practice (forking and adding one's own template changes is no fun).

One minor change request to point users to the relevant K8S object reference doc. Sadly no way to not pin that to a specific version yet, but that's a fairly minor concern--I'm fine pointing that to current latest/v18 and leaving it up to readers to figure out if they need to change to an older or newer version.

2020-07-23 19:35 UTC, dsem commented
Thanks for the feedback and so glad you'll find it helpful too!

2020-07-24 20:10 UTC, rainest commented
Passes all practical testing on my end! :shipit: 

Thank you for your contribution. Please fill out the following form to claim your contributor swag:
https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt.

2020-07-24 20:11 UTC, rainest approved these changes

2020-07-24 20:11 UTC, merged

2020-09-11 23:25 UTC, hbagdi commented
Thank you for your contribution. Please fill out the following form to claim your contributor swag:
https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt.