[repo] update references from master to main
Kong/charts pull request #177
Opened 2020-07-31 20:42 UTC by rainest

#### What this PR does / why we need it:
Updates documentation and CI configuration to use `main` instead of `master`.

#### Special notes for your reviewer:
KIC/Kong links remain to `master`, as those have not changed yet.

2020-08-01 13:17 UTC, mflendrich requested changes
Looks good :+1: but one link appears broken (fix attached). Also don't forget about setting GitHub Pages behind charts.konghq.com to track `main` instead of `master`.

2020-08-03 16:07 UTC, mflendrich approved these changes

2020-08-03 16:07 UTC, rainest commented
Do we have existing pages for this?

I don't have actual ownership of the repo, so will need Harry's assistance for making the actual GitHub-level changes. We should perhaps adjust that for this and the operator repo.

2020-08-03 16:07 UTC, merged

2020-08-03 16:08 UTC, mflendrich commented
> Do we have existing pages for this?

https://charts.konghq.com/ which seems to point at https://kong.github.io/charts/