[kong] Add custom extra configmaps/secrets
Kong/charts pull request #208
Opened 2020-10-05 18:39 UTC by mikemenaker

Add extraConfigMaps and extraSecrets fields to values file that will be added to volumes/volumeMounts template helpers.

#### What this PR does / why we need it:
Adds ability to mount arbitrary config maps/secrets

#### Which issue this PR fixes
closes #196 #196

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ X] PR is based off the current tip of the `next` branch and targets `next`, not `main`
- [X ] New or modified sections of values.yaml are documented in the README.md
- [ X] Title of the PR and commit headers start with chart name (e.g. `[kong]`)

2020-10-05 18:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=208) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=208) before we can accept your contribution.<br/><hr/>**Mike Menaker** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=208) it.</sub>

2020-10-12 21:46 UTC, rainest requested changes
Woo, finally got a chance to play around with this after Kong Summit stuff. We had some history issues with our release process as part of that, so you'll want to merge in the latest `next` tip.

Generally looks good as far as mounting stuff, but I have one change request and one question that's probably also a change request. Simpler one first!

For the comments, I'd suggest making the inline comments a double-comment with some brief explanation, so that removing the leading `#` doesn't include anything that will parse as YAML other than the the example string itself, e.g. 


```
#   subPath: my-subpath # Optional, if you wish to mount a single key and not the entire ConfigMap
```
instead of:

```
#   subPath: my-subpath [OPTIONAL]
```
More complex one second: do you know of any reason to include the `readOnly` field? That looks like maybe some confusion introduced by the K8S docs and volume mount spec, which address all types of volume mounts equally. As best I can tell, R/W ConfigMap or Secret mounts aren't actually allowed, so I'd say remove that setting (and the associated template content) unless you know of some edge case that'd require it still.

ConfigMap/Secret mounts appear to be [read-only always](https://github.com/kubernetes/kubernetes/issues/62099#issuecomment-527286207), and K8S will just ignore silently ignore that setting for them. Per the other issue comments, this behavior is itself a source of confusion, but apparently exists as a legacy holdover from when K8S _did_ allow you to modify mounted ConfigMaps and Secrets.

2020-10-15 04:02 UTC, mikemenaker commented
I updated the fork with the requested changes, I'll merge/rebase the last 'next' branch tomorrow morning.

2020-10-16 23:21 UTC, rainest approved these changes

2020-10-16 23:58 UTC, rainest commented
Bizarre. CI keeps failing because a Postgres-backed instance cannot connect to Postgres, but I cannot replicate this locally with the same test values on a fresh install/namespace.

Possibly something awry with GH actions at the moment; will try tests again on Monday.

2020-10-19 19:50 UTC, merged