[kong] add missing root object type to CRD OpenAPI v3 schema
Kong/charts pull request #358
Opened 2021-05-10 10:47 UTC by Starefossen

#### What this PR does / why we need it:

Currently all installed CRDs are throwing violations warnings due to missing root type values.

```
kubectl describe crd kongconsumers.configuration.konghq.com
...
Status:
  Accepted Names:
    Kind:       KongConsumer
    List Kind:  KongConsumerList
    Plural:     kongconsumers
    Short Names:
      kc
    Singular:  kongconsumer
  Conditions:
    Last Transition Time:  2021-01-20T14:41:12Z
    Message:               spec.versions[0].schema.openAPIV3Schema.type: Required value: must not be empty at the root
``` 

See the following for more information on this topic:

* https://github.com/kubernetes/kubernetes/issues/81445
* https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

OpenAPI will not be published to `kubectl explain` unless we also set `preserveUnknownFields: false` or set the `apiVersion: apiextensions.k8s.io/v1` (it is `v1beta1` today).

```
kubectl explain kongingress
KIND:     KongIngress
VERSION:  configuration.konghq.com/v1

DESCRIPTION:
     <empty>
```

See https://github.com/kubernetes/kubernetes/issues/95702 for more info on this topic.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] PR is based off the current tip of the `next` branch and targets `next`, not `main`
- [ ] New or modified sections of values.yaml are documented in the README.md
- [ ] Title of the PR and commit headers start with chart name (e.g. `[kong]`)

2021-05-10 10:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=358) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=358) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=358) it.</sub>

2021-05-10 10:49 UTC, Starefossen commented on charts/kong/crds/custom-resource-definitions.yaml
> +          type: object
This was also missing and throws a similar error.

2021-05-12 13:20 UTC, mflendrich commented
Thanks @Starefossen for your contribution.

Could you please make this change instead to the CRDs defined in [this file](https://github.com/Kong/kubernetes-ingress-controller/blob/next/deploy/manifests/base/custom-types.yaml) in the Kong/kubernetes-ingress-controller repo? You'll also need to run the `hack/build-single-manifests.sh` scritpt there when you're done.

We have some changes there not yet promoted to the helm chart. Also, it's the KIC repo that's the source of truth for CRDs.

2021-05-12 13:21 UTC, mflendrich requested changes
Thanks @Starefossen for your contribution.

Could you please make this change instead to the CRDs defined in [this file](https://github.com/Kong/kubernetes-ingress-controller/blob/next/deploy/manifests/base/custom-types.yaml) in the Kong/kubernetes-ingress-controller repo? You'll also need to run the `hack/build-single-manifests.sh` scritpt there when you're done.

We have some changes there not yet promoted to the helm chart. Also, it's the KIC repo that's the source of truth for CRDs.

2021-06-02 21:15 UTC, closed without merging