[kong] initContainer for job #390
Kong/charts pull request #408
Opened 2021-07-20 05:22 UTC by ttony

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #390 

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `next` branch and targets `next`, not `main`
- [x] Title of the PR and commit headers start with chart name (e.g. `[kong]`)

2021-07-21 22:40 UTC, rainest requested changes
Gotcha re the [`tpl` use description in the previous PR](https://github.com/Kong/charts/pull/397#issuecomment-883036453). I'd still request removing that and using plain `toYaml` only. The meta-templating enabled by using content elsewhere in values.yaml as an injected user template feels overcomplicated, so absent demand from additional users I'd like to avoid it.

As an alternative I'd suggest pre-processing values.yamls with another templating engine to fill in those blocks prior to passing it to Helm. That allows for the same end result and, as a general strategy, is more flexible, as it doesn't rely on specific parts of the chart template using `tpl`.

https://github.com/noqcks/gucci can be used as a standalone template renderer that supports the same capabilities as Helm's standard template engine (since it's Golang templating with the sprig library included).

2021-07-25 09:50 UTC, ttony commented
for tpl related, i will removed it soon. aside of this, we can ask for vote on the community about tpl feature which supported in helm. as it is very handy and bundled function as part of helm instead of rely of another different tools.

2021-07-26 23:21 UTC, rainest approved these changes

2021-07-26 23:22 UTC, merged

2021-07-26 23:29 UTC, rainest commented
> aside of this, we can ask for vote on the community about tpl feature

Yeah, feel free to create an issue outlining the proposed change, and we'll await input from other users looking for something similar and/or note down when it'd be useful for handling some other need.