feat(helpers) add non-KONG prefixed env
Kong/charts pull request #530
Opened 2022-01-19 22:30 UTC by ksubburayalu

#### What this PR does / why we need it:
Various use cases where customers need non-prefixed environment variables to accessed in custom plugins or serverless functions. Example of these variables include upstream api_tokens or credentials that customer doesn't want to be shown clear text in the plugin configurations. 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] PR is based off the current tip of the `main` branch.
- [ ] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2022-01-19 22:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=530) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=530) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=530) it.</sub>

2022-01-20 18:30 UTC, rainest requested changes
Generally looks good. Can you add a `customEnv` entry to one of the `ci/testN-values.yaml` and a CHANGELOG.md entry under the unreleased section?

2022-01-20 20:42 UTC, ksubburayalu commented
Added `customEnv` entry in `ci/test5-values.yaml` and updated CHANGElog.md as well.

2022-01-20 21:17 UTC, rainest approved these changes

2022-01-20 21:17 UTC, merged