preStop: Replace sleep with --wait
Kong/charts pull request #531
Opened 2022-01-20 16:26 UTC by dcarley

#### What this PR does / why we need it:

The `kong quit` command has the ability to do the sleep itself which is
cleaner and provides better logging (should we choose to capture it):

- https://github.com/Kong/kong/blob/2.6.0/kong/cmd/quit.lua#L59-L72
- https://github.com/Kong/kong/blob/2.6.0/kong/cmd/quit.lua#L20-L33

#### Which issue this PR fixes
N/A

#### Special notes for your reviewer:
We've been testing this because the wait needs to be increased when using NLBs.

I've only quoted the last argument because it has more chance of falling foul of YAML intepretation.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `main` branch.
- [x] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2022-01-20 18:32 UTC, shaneutt submitted a review, later dismissed

2022-01-20 18:33 UTC, rainest requested changes
Minor change to link the PR, otherwise LGTM.

2022-01-20 18:33 UTC, rainest commented on charts/kong/CHANGELOG.md
> +* Replaced `sleep 15` in `preStop` command with `--wait=15` argument to `kong quit`.
```suggestion
* Replaced `sleep 15` in `preStop` command with `--wait=15` argument to `kong quit`.
  ([#531](https://github.com/Kong/charts/pull/531))
```

2022-01-21 09:44 UTC, dcarley commented on charts/kong/CHANGELOG.md
> +* Replaced `sleep 15` in `preStop` command with `--wait=15` argument to `kong quit`.
I've rebased to include 👍🏻

2022-01-21 16:31 UTC, rainest approved these changes

2022-01-21 16:34 UTC, merged