feat(conf) add sidecar containers to migration pods
Kong/charts pull request #540
Opened 2022-02-05 00:34 UTC by Mirdrack

#### What this PR does / why we need it:
The side containers are only included in the main deployment
definition, these updates include the sidecar containers definition
into the migration pods definitions allowing the implementation of the
sidecar pattern on the migration handleiding

Now sidecars will be able for migrations, pre-upgrade and post-upgrade
containers.

#### Which issue this PR fixes
None

#### Special notes for your reviewer:
This PR was motivated for being unable to run the migrations on a system that is using a sql proxy as a sidecar for the database connection
Sidecar containers are already documented but not sure if I should add an extra note about this

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `main` branch.
- [ ] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [ ] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2022-02-05 00:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=540) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=540) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=540) it.</sub>

2022-02-07 20:07 UTC, rainest requested changes
This needs to be a separate `migrations.sidecarContainers` key, since not all sidecars are appropriate for the Jobs. If the sidecar runs indefinitely, the Job will not actually complete. I'm actually surprised that the SQL proxy wouldn't have the same issue; do you have a means of terminating it once the main container is done?

Can you also test cases for these to ci/test2-values.yaml?

```
deployment:
  kong:
    sidecarContainers:
      - name: sidecar
        image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
migrations:
  sidecarContainers:
     - name: sidecar
       image: bash:4.4
       args: ["true"]
```

2022-02-14 03:05 UTC, Mirdrack commented
Thank you @rainest you helped me realize one of my mistakes running the migrations. Indeed, the proxy sidecar container never stops and the deployment of the chart fails.
Regardless, I think that it would be nice to have the option to include sidecars on the migration containers with the disclaimer that they should be finite.

2022-02-14 19:11 UTC, rainest approved these changes

2022-02-14 19:15 UTC, merged