feat(pathType) support user-defined ingress pathType
Kong/charts pull request #564
Opened 2022-03-22 08:10 UTC by vzell

Add support for user-defined ingress pathType. Right now it was hard-coded to be `ImplementationSpecific`.
According to https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types the values can be one of
`ImplementationSpecific`, `Exact` or `Prefix`.

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] PR is based off the current tip of the `main` branch.
- [ ] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [ ] New or modified sections of values.yaml are documented in the README.md
- [ ] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2022-03-22 08:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=564) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=564) before we can accept your contribution.<br/><hr/>**Volker Zell** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=564) it.</sub>

2022-03-22 22:22 UTC, rainest commented
@vzell can you share what prompted this? For the various Kong services, I'd expect that you only ever want prefix behavior, since they all expose many more endpoints than their Ingress lists (e.g. for the admin API you want to match requests for both `/` and `/routes`).

ImplementationSpecific for Kong is de facto prefix (though it does not require a trailing slash, which the Ingress Prefix spec does), and as far as we know that works fine for all our services, so it was originally omitted to reduce the number of configuration options, with the expectation that there'd be no reason to change it in practice.

2022-03-23 07:12 UTC, vzell commented
@[rainest](https://github.com/rainest) Our use case on Amazon EKS only works with pathType `Prefix`. Until now it was hardcoded to be `ImplementationSpecific` and I could not overwrite it which prompted me to the patch.

2022-03-23 17:03 UTC, rainest requested changes
Sounds reasonable--to clarify, you're handling them through the ALB controller instead of ours then?

If you can the following to the changelog under the Unreleased > Improvements section we should be all set:

```
* Ingress `pathType` field is now configurable.                                                                                             
  ([564](https://github.com/Kong/charts/pull/564))
```

2022-03-23 20:43 UTC, vzell commented
Yes, we are handling them through the ALB controller...

Added to CHANGELOG

2022-03-23 23:10 UTC, rainest approved these changes

2022-03-23 23:19 UTC, merged