doc(examples) add hybrid enterprise example values
Kong/charts pull request #575
Opened 2022-04-07 15:37 UTC by PhilKuer

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `main` branch.
- [] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2022-04-07 15:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/Kong/charts?pullRequest=575) <br/>All committers have signed the CLA.

2022-04-07 17:27 UTC, rainest requested changes
Mostly stripping values that are already present in the default values.yaml.

Removed the changelog since it was causing a merge conflict and we don't usually cover docs changes there anyway.

2022-04-07 17:27 UTC, rainest commented on charts/kong/example-values/minimal-kong-enterprise-hybrid-control.yaml
> +    containerPort: 8005
The ports are unchanged from the defaults so shouldn't be set here also:

```suggestion
admin:
  enabled: true
  http:
    enabled: true

cluster:
  enabled: true
  tls:
    enabled: true
```

2022-04-07 17:27 UTC, rainest commented on charts/kong/example-values/minimal-kong-enterprise-hybrid-control.yaml
> +  prefix: /kong_prefix/
Included in the default values.
```suggestion
```

2022-04-07 17:27 UTC, rainest commented on charts/kong/example-values/minimal-kong-enterprise-hybrid-control.yaml
> +    database: kong
```suggestion
```

2022-04-07 17:27 UTC, rainest commented on charts/kong/example-values/minimal-kong-enterprise-hybrid-control.yaml
> +    enabled: false
```suggestion
```

2022-04-07 17:27 UTC, rainest commented on charts/kong/example-values/minimal-kong-enterprise-hybrid-data.yaml
> +  prefix: /kong_prefix/
```suggestion
```

2022-04-07 17:27 UTC, rainest commented on charts/kong/example-values/minimal-kong-enterprise-hybrid-data.yaml
> +    enabled: false
```suggestion
  portal:
    enabled: false
  rbac:
    enabled: false
```

2022-04-07 17:27 UTC, rainest commented on charts/kong/CHANGELOG.md
> +
```suggestion
```

2022-04-08 05:26 UTC, PhilKuer commented
Thanks for your feedback.

I have stripped both example-values to match the default values. Changelog line is also removed.

2022-04-08 16:52 UTC, rainest approved these changes

2022-04-08 17:02 UTC, merged