chore: bump controller version to 2.4
Kong/charts pull request #627
Opened 2022-07-04 09:07 UTC by pmalek

#### What this PR does / why we need it:

Bumps KIC version to "2.4"

#### Special notes for your reviewer:

#### Checklist

- [x] PR is based off the current tip of the `main` branch.
- [x] Changes are documented under the "2.11.0" header in CHANGELOG.md
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2022-07-04 09:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=627) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=627) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=627) it.</sub>

2022-07-04 09:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=627) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=627) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=627) it.</sub>

2022-07-04 11:00 UTC, jrsmroz submitted a review, later dismissed

2022-07-05 18:06 UTC, rainest requested changes
We'll actually want to use `"2.4"` and `2.10.3`. We don't consider default version bumps a minor version change since they should only affect new installs--properly-configured releases should pin their image versions.

The KIC repo manifests do use the full version because they're tagged along with that specific release--if you get the manifest for tag 2.4.1, it should indeed install 2.4.1 even if there's a newer patch available. The chart isn't so tightly coupled and we want the version that will get new patch versions as they roll out.

Edit: well, actually just strip the chart bump altogether. There are a few changes in flight and it'll be easier to release them all at once.

2022-07-05 18:41 UTC, pmalek commented
@rainest 👍 PTAL now

2022-07-05 18:51 UTC, jrsmroz commented
> We'll actually want to use `"2.4"` and `2.10.3`. We don't consider default version bumps a minor version change since they should only affect new installs--properly-configured releases should pin their image versions.
> 

Thanks for the clarification, I was not aware of this.

2022-07-05 18:52 UTC, jrsmroz commented
@pmalek Please change the PR title too.

2022-07-05 18:56 UTC, pmalek commented
@rainest BTW: what you're trying to say is that by bumping to 2.4 the user will ultimately get latest patch from 2.4.x?

2022-07-05 19:08 UTC, rainest approved these changes
@pmalek yes, we push a minor `x.y` tag every time we release, so it points to the latest patch for that minor.

Some added changes to back out the release and drop a changelog item we shouldn't have had (it was docs only).

2022-07-05 19:13 UTC, merged