Size limits for Empty Dirs
Kong/charts pull request #632
Opened 2022-07-06 18:52 UTC by chaitanya14

#### What this PR does / why we need it:

Empty directory without size limit is consuming all the ephemeral local storage resources. Need to have a capability to assign limits on it. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `main` branch.
- [x] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [ ] New or modified sections of values.yaml are documented in the README.md
- [ ] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2022-07-06 18:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=632) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=632) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=632) it.</sub>

2022-07-06 19:25 UTC, rainest commented
What were you seeing these growing to in practice? What were the largest files in the mounts?

I'd prefer to make these static limits rather than configurable if possible, since they should be small and consistent enough in size that users shouldn't need to worry about configuring them. I don't know offhand what'd consume much space in those locations other than logs (which we want to divert to stdout and stderr)--I'm checking with the gateway engineers, but info from your instance would be helpful.

If we do end up using configurable values, they need to be in the default values.yaml and in documentation, else you'll hit the error that's currently failing in CI:

```
Error:  templates/: template: kong/templates/deployment.yaml:288:10: executing "kong/templates/deployment.yaml" at <include "kong.volumes" .>: error calling include: template: kong/templates/_helpers.tpl:414:25: executing "kong.volumes" at <.Values.deployment.prefixDir.sizeLimit>: nil pointer evaluating interface {}.sizeLimit
```

2022-07-07 03:39 UTC, chaitanya14 commented
> What were you seeing these growing to in practice? What were the largest files in the mounts?
> 
> I'd prefer to make these static limits rather than configurable if possible, since they should be small and consistent enough in size that users shouldn't need to worry about configuring them. I don't know offhand what'd consume much space in those locations other than logs (which we want to divert to stdout and stderr)--I'm checking with the gateway engineers, but info from your instance would be helpful.
> 
> If we do end up using configurable values, they need to be in the default values.yaml and in documentation, else you'll hit the error that's currently failing in CI:
> 
> ```
> Error:  templates/: template: kong/templates/deployment.yaml:288:10: executing "kong/templates/deployment.yaml" at <include "kong.volumes" .>: error calling include: template: kong/templates/_helpers.tpl:414:25: executing "kong.volumes" at <.Values.deployment.prefixDir.sizeLimit>: nil pointer evaluating interface {}.sizeLimit
> ```

I don't have certain numbers on limits but we are facing disk pressure issues on AKS nodes. These directories may or may not be directly effecting our issue but as a best practice it is better to evict the pods if empty dirs are using more ephemeral storage  than defined. This will improve things only.

2022-07-07 03:43 UTC, chaitanya14 commented
> > What were you seeing these growing to in practice? What were the largest files in the mounts?
> > I'd prefer to make these static limits rather than configurable if possible, since they should be small and consistent enough in size that users shouldn't need to worry about configuring them. I don't know offhand what'd consume much space in those locations other than logs (which we want to divert to stdout and stderr)--I'm checking with the gateway engineers, but info from your instance would be helpful.
> > If we do end up using configurable values, they need to be in the default values.yaml and in documentation, else you'll hit the error that's currently failing in CI:
> > ```
> > Error:  templates/: template: kong/templates/deployment.yaml:288:10: executing "kong/templates/deployment.yaml" at <include "kong.volumes" .>: error calling include: template: kong/templates/_helpers.tpl:414:25: executing "kong.volumes" at <.Values.deployment.prefixDir.sizeLimit>: nil pointer evaluating interface {}.sizeLimit
> > ```
> 
> I don't have certain numbers on limits but we are facing disk pressure issues on AKS nodes. These directories may or may not be directly effecting our issue but as a best practice it is better to evict the pods if empty dirs are using more ephemeral storage than defined. This will improve things in kubernetes cluster .

Also, we have a data plane where we have used 256Mi size of empty dirs that never caused an issue since 4 months. So IMO default to 256Mi is more meaningful.

2022-07-07 17:05 UTC, rainest requested changes
We'll want to merge https://github.com/Kong/charts/pull/634 first. Several of those were wrong and would eventually fill the prefix on a long-lived Pod.

There's one unbounded consumer of /tmp/ space whose actual needs will vary depending on use characteristics, so we do indeed need to make these configurable. NGINX will buffer large client bodies to disk, and we [set no default upper bound on their size](https://github.com/Kong/kong/blob/5d721ac9ae1df36049013599d0253bd39cb6f758/kong.conf.default#L919-L949). An instance with a large number of concurrent large bodies (e.g. something that handles video uploads) is expected to consume a bunch of /tmp/ space even though most instances won't, so IMO we should give that one more breathing room.

2022-07-07 17:05 UTC, rainest commented on charts/kong/values.yaml
> +    sizeLimit: 256Mi
```suggestion
    sizeLimit: 1Gi
```

2022-07-07 18:36 UTC, rainest requested changes

2022-07-07 18:36 UTC, rainest commented on charts/kong/values.yaml
> +  # tmp empty dir size
```suggestion
  # tmp empty dir size
```

2022-07-07 21:03 UTC, rainest approved these changes

2022-07-07 21:09 UTC, merged

2022-07-07 21:14 UTC, chaitanya14 commented
@rainest  When will this be released ?

2022-07-07 21:20 UTC, rainest commented
Probably end of this week or start of next; there are a few other things I'd like to work in if possible.

2022-07-08 16:34 UTC, pmalek commented on charts/kong/CHANGELOG.md
> +###
We missed a section name in here I suppose