[kong] add upgrade documentation
Kong/charts pull request #74
Opened 2020-03-13 18:59 UTC by rainest

#### What this PR does / why we need it:
Adds dedicated UPGRADE.md for detailed upgrade instructions. It also fixes some minor errors in other docs.

#### Special notes for your reviewer:
As written, this assumes that #72 will be released as part of 1.4.0.

NOTES.txt should be updated to refer to the instructions in UPGRADE.md, but holding off on that for now since it'd conflict with the open changes in #72.

#### Checklist
- [x] PR is based off the current tip of the `next` branch and targets `next`, not `master`
- [x] Title of the PR and commit headers start with chart name (e.g. `[kong]`)

2020-03-17 17:34 UTC, hbagdi requested changes

2020-03-17 17:34 UTC, hbagdi commented on charts/kong/README.md
>  - [Helm 2 vs Helm 3](#important-helm-2-vs-helm-3)
Please add a link to the upgrade document in this README.

2020-03-17 18:19 UTC, rainest commented on charts/kong/UPGRADE.md
> +clear it.
There generally shouldn't be any reason to handle these independently. Backwards compatibility between the chart and Kong versions isn't firmly defined yet, but generally trends towards going back as far as reasonable based on what versions we encounter in practice.

Once we have more defined EOL on Kong releases themselves we can move towards officially ending older version support, but I'll probably put notes to that effect in the individual version upgrade section.

Did add a blurb about checking before skipping Kong versions though.

2020-03-17 20:55 UTC, hbagdi commented on charts/kong/UPGRADE.md
> +clear it.
> There generally shouldn't be any reason to handle these independently.

When things do go wrong, it becomes cumbersome to figure out what went wrong. It is rarely Kong migrations but usually some setting in Kubernetes. Reducing the delta and making smaller changes certainly help users and us (when we want to help out users).

I agree we don't define and don't have an official stand on backwards compatibility but we the effort we make for backwards compatibility tells me that most customers will be able to achieve what I'm recommending above.

2020-03-19 20:08 UTC, hbagdi commented on charts/kong/UPGRADE.md
> +clear it.
Ping for above. All else looks good.

2020-03-19 21:50 UTC, hbagdi approved these changes

2020-03-19 21:51 UTC, merged