Webhook validation labels
Kong/charts pull request #768
Opened 2023-03-13 03:36 UTC by minfeng-chan

#### What this PR does / why we need it:
This pull request adds label to the validation webhook. 
This is necessary for certain use cases such as integrating with Consul. 
For consul we will need to add the following:
consul.hashicorp.com/service-ignore: "true"

#### Which issue this PR fixes
NIL

#### Special notes for your reviewer:
NIL 

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `main` branch.

2023-03-13 03:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=768) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=768) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=768) it.</sub>

2023-03-14 19:55 UTC, rainest requested changes
Looks reasonable. @minfeng-chan can you add a changelog entry and sign the CLA? That should be all we need to merge this.

2023-03-31 01:48 UTC, minfeng-chan commented
Hi rainest, edited as per your comment. Thanks.

2023-03-31 11:10 UTC, czeslavo approved these changes

2023-03-31 16:56 UTC, rainest approved these changes

2023-03-31 16:56 UTC, merged