[kong] add support for watch-namespace
Kong/charts pull request #79
Opened 2020-03-19 21:59 UTC by wopol

Adding support for watch-namespace in chart

2020-03-19 21:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=79) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=79) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=79) it.</sub>

2020-03-20 02:34 UTC, hbagdi commented
Can you change this to instead inject arbitrary CLI arguments to the controller?
Something along the lines of taking in an array of strings and passing it verbatim to the controller.

We need to do this to make it easy enough for folks to override other properties via CLI flags.

2020-03-20 17:05 UTC, wopol commented
Yes, i can do this. Did you mean something like that?
```
ingressController:
  installCRDs: false
  ingressClass: myClass
  rbac:
    create: false
  serviceAccount:
    create: false
    name: sa-name
  args:
    - --watch-namespace=namespace-name
    - --other-arg=value
```
And one more question. What  with hardcoded arguments in `kong.controller-container` function  like `admin-tls-skip-verify`, `--admission-webhook-listen` etc.  Should these arguments stay there?

2020-03-20 17:14 UTC, hbagdi commented
> Should these arguments stay there?

No. Let's move them over to the values.yaml file as well so that a user can change them, if needed.

2020-03-20 18:07 UTC, wopol commented
> > Should these arguments stay there?
> 
> No. Let's move them over to the values.yaml file as well so that a user can change them, if needed.

Now this is a little bit more complicated, but we have all default arguments and we can replace them when we define the same argument in args Map.

2020-03-20 18:41 UTC, hbagdi commented
> Now this is a little bit more complicated, but we have all default arguments and we can replace them when we define the same argument in args Map.

In values.yaml, we can simply add and keep this simple:
```yaml
ingressController
  args:
  - --flag=value1
  - --bolean-flag
  - --flag2=value2
```

Users  can inject any flag and edit the default as well.

2020-03-20 18:55 UTC, wopol commented
> > Now this is a little bit more complicated, but we have all default arguments and we can replace them when we define the same argument in args Map.
> 
> In values.yaml, we can simply add and keep this simple:
> 
> ```yaml
> ingressController
>   args:
>   - --flag=value1
>   - --bolean-flag
>   - --flag2=value2
> ```
> 
> Users can inject any flag and edit the default as well.

I prefer simple solution but what if someone use arguments like that:
```
ingressController:
  ingressClass: other-class
  args:
    - --ingress-class=class-name
    - --publish-service=name
```

Which values should have higher priority for `--ingress-class` ingressController.ingressClass or ingressController.args[0] ?
Which values should have higher priority for `--publish-service` ingressController.args[1] or `{{ .Release.Namespace }}/{{ template "kong.fullname" . }}-proxy`

2020-03-20 19:00 UTC, hbagdi commented
> Which values should have higher priority for --ingress-class ingressController.ingressClass or ingressController.args[0] ?

Specifying via args should have a higher priority.

Some background:
We do want to add arg based approach, but we will recommend using environment variables for all configuration changes, especially to these ones that are already supported by environment variables.

Only logging based variables are not yet supported by environment variables, which is why we want to merge this PR in.
Flag/env should take precedence over specifying the value directly using a chart variable, like `ingressClass`.

2020-03-20 19:19 UTC, wopol commented
> Only logging based variables are not yet supported by environment variables, which is why we want to merge this PR in.
> Flag/env should take precedence over specifying the value directly using a chart variable, like `ingressClass`.

This will be more difficulty and less readable to check if in args array exist some key when not exist generate default e.g `election-id=kong-ingress-controller-leader-{{ .Values.ingressController.ingressClass }}`
I will try to do it

2020-03-20 20:19 UTC, hbagdi commented on charts/kong/templates/_helpers.tpl
> +
Please remove these line jumps.

2020-03-20 20:21 UTC, hbagdi commented
This looks good to me since going forward, users should add CLI args only for logging related settings.
The existing CLI flags will be moved over to environment variables after controller 0.8 is released, and we already have good amount of code on how to set precedence there.
@rainest thoughts?

2020-03-20 20:25 UTC, wopol commented on charts/kong/templates/_helpers.tpl
> +
Done

2020-03-20 22:02 UTC, rainest commented
@hbagdi you mean migrate `kong.ingressController.env` to something like `kong.env`'s dict-based deduplication system and handle all defaults via environment variables? That seems reasonable.

Post-0.8 is there any reason you'd still use CLI arguments over their equivalent variable? It almost seems like it'd make more sense to wait and have users use environment variables only, since we wouldn't have any means of avoiding conflicts between envvar/CLI settings.

2020-03-20 22:53 UTC, hbagdi commented
> dict-based deduplication system and handle all defaults via environment variables?

Yes.

> Post-0.8 is there any reason you'd still use CLI arguments over their equivalent variable? It almost seems like it'd make more sense to wait and have users use environment variables only, since we wouldn't have any means of avoiding conflicts between envvar/CLI settings.

Yes, because https://github.com/Kong/kubernetes-ingress-controller/issues/506.
Hence, the comment on logging CLI args only. Everything else will move to env vars.
We should move logging CLI args to env vars as well but that's not a priority (for me at least).

2020-03-20 22:58 UTC, rainest submitted a review, later dismissed
Ah, okay, I thought 0.8 was going to add support also.

2020-03-20 23:01 UTC, hbagdi requested changes
This is looking good and we would like to merge it in.
Please also add a test case to an existing test (don't add another test file as it puts pressure on the CI).
Add a harmless argument like `--ingress-class=test-kong` or something like that. A logging arg would be even better. Full list here: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/references/cli-arguments.md.


Thank you for pushing through this even though the purpose of the PR changed significantly.

2020-03-23 17:39 UTC, hbagdi approved these changes

2020-03-23 17:40 UTC, merged

2020-04-22 23:43 UTC, hbagdi commented
@wopol  Thank you for your contribution. Please fill in the contributor form to claim your Kong swag: https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#contributor-t-shirt.