feat(kong): fail to render templates when PodSecurityPolicy is requested but cluster doesn't serve it
Kong/charts pull request #823
Opened 2023-06-20 10:28 UTC by pmalek

#### What this PR does / why we need it:

When PSP is requested via `.Values.podSecurityPolicy` but cluster cannot serve it then fail to render instead of silently ignoring.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `main` branch.
- [x] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2023-06-20 19:20 UTC, rainest commented
We don't have a way to make CI expect failures like these on cluster versions where we expect them, correct? Do we simply have to remove coverage for this to make chart-testing not complain "hey! this failed to install!" (as it should)?

2023-06-20 19:39 UTC, pmalek commented
> We don't have a way to make CI expect failures like these on cluster versions where we expect them, correct? Do we simply have to remove coverage for this to make chart-testing not complain "hey! this failed to install!" (as it should)?

There might be a way but I don't know it off the top of my head

2023-06-21 17:09 UTC, rainest requested changes
I don't see anything in chart-testing that suggests it would, so go ahead and just strip the PSP setting out of ci/test1-values.yaml

Realistically, PSP hasn't changed in a while, isn't likely to change going forward (since it no longer exists in current versions), and isn't likely to be broken by changes elsewhere (or rather, if we break something like the namespace or SA templates, that will break other resources also).

2023-06-22 08:22 UTC, pmalek commented
> I don't see anything in chart-testing that suggests it would, so go ahead and just strip the PSP setting out of ci/test1-values.yaml
> 
> Realistically, PSP hasn't changed in a while, isn't likely to change going forward (since it no longer exists in current versions), and isn't likely to be broken by changes elsewhere (or rather, if we break something like the namespace or SA templates, that will break other resources also).

👍 Done.

It seems that if we ever wanted to do something like this we'd need to provide a matrix similarly as [it's done for "integration" tests ](https://github.com/Kong/charts/blob/21ec72e9e2b716dd119bc093dba36a403334191a/.github/workflows/main-pr.yaml#L85-L104) and somehow map test values against those versions.

2023-06-22 17:02 UTC, rainest approved these changes

2023-06-22 17:02 UTC, merged