feat: set default router flavor to expressions if KIC >=3.0 and traditional_compatible otherwide
Kong/charts pull request #935
Opened 2023-11-09 07:48 UTC by randmonkey

#### What this PR does / why we need it:

Add `kong.router_flavor` to set router flavor to:
- `values.env.router_flavor` if specified
- `expressions` if KIC is enabled and image version >= 3.0.0
- `traditional_compatible` otherwise (REVIEW: is it better to leave it empty to let Kong gateway to use the default value)?

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes https://github.com/Kong/kubernetes-ingress-controller/issues/5129

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] PR is based off the current tip of the `main` branch.
- [ ] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [ ] New or modified sections of values.yaml are documented in the README.md
- [ ] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2023-11-09 09:24 UTC, czeslavo commented on charts/kong/templates/_helpers.tpl
> +        traditional_compatible
As I understand this also changes the default when KIC is < 3.0.0 from `traditional` to `traditional_compatible`, is this intended?

2023-11-09 09:38 UTC, pmalek commented
> REVIEW: is it better to leave it empty to let Kong gateway to use the default value

On one hand setting this in chart makes this predictable for us. Regardless of Kong Gateway version we use as default, we'll always get the expected behavior. On the other hand though, users might be expecting the Gateway defaults to translate into corresponding chart settings.

We've had a long history of **setting** the router flavor so I'd say we retain this and keep setting it in the chart. If there'a debate we'd like to have on this I suggest we consider pros and cons of that in a separate issue.

2023-11-09 09:39 UTC, pmalek commented on charts/kong/templates/_helpers.tpl
> +        traditional_compatible
👍 on keeping whatever was the default - `traditional` for KIC <3.0.

2023-11-09 09:52 UTC, czeslavo requested changes
As mentioned on the team sync, we have to keep in mind this won't work as expected with `kong/ingress` chart. `gateway` part of the release doesn't know about the `controller`'s `ingressController.image`. The condition will be executed based on the `gateway`'s `ingressController.image` (which will be the default from `values.yaml` - so we accidentally get KIC 3.0 there _always_ if a user for some weird reason didn't change `gateway.ingressController.image` to something else). 

As an example, this change will break Konnect `values.yaml` where we still want to keep using `traditional_compatible` router with KIC 2.11/2.12:

```
controller:
  ingressController:
    image:
      tag: "2.11"
...

gateway:
  image:
    repository: kong/kong-gateway
    tag: "3.4"
...
 ```

~As this will pick `expressions` based on the default value of `gateway.ingressController.image` which is 3.0 now.~

EDIT after checking actual results: As in the template there's `.Values.ingressController.enabled` condition required to set router flavor to `expressions`, for `kong/ingress` chart this will always default to `traditional_compatible`. The problem persists though because the router flavor is not changed based on the KIC version as intended. So, if we set `controller.ingressController.image.tag` to `3.0` to start using KIC 3.0 in `kong/ingress`, Gateway's router flavor will still default to `traditional_compatible`.

I think we have to either:
- Wait for @rainest's https://github.com/Kong/charts/pull/923
- Add some templating to `kong/ingress` that will somehow override `gateway.ingressController.image` to what is set in `controller.ingressController.image`.

2023-11-09 13:24 UTC, czeslavo commented
I was trying to come up with some workaround that would make this work with `kong/ingress`, but I couldn't achieve anything that would satisfy the requirement of `helm install kong kong/ingress` just setting the expression router based on controller image tag. 😞 

I was trying to use `.Values.global` or templates to override values of the `gateway` subchart using values of the `controller`, but that is not possible (there was a proposal in Helm charts repo implementing that, but it was rejected: https://github.com/helm/helm/pull/6876). 

The only more-or-less reasonable way I came up with was adding a new variable in `kong/kong` values (`deployment.kong.alignWithControllerVersion`) that could allow users to explicitly tell to auto-align gateway's config based on a given controller version. https://github.com/Kong/charts/pull/936 But of course, it has drawbacks, e.g. requires setting an additional value.

I think I just assured myself that https://github.com/Kong/charts/pull/923 is the only way we can make it work as we expected.

2023-11-09 13:36 UTC, pmalek commented
I couldn't find the helm doc page on this but `.Subcharts` seems to be the thing that we're looking for (at least as a workaround until/if we get to the split Deployment in `kong` chart).

https://github.com/Kong/charts/pull/937 shows how it could be used to enforce the router flavor in `ingress` chart using subcharts values.

2023-11-09 13:42 UTC, czeslavo commented
> I couldn't find the helm doc page on this but `.Subcharts` seems to be the thing that we're looking for (at least as a workaround until/if we get to the split Deployment in `kong` chart).
> 
> #937 shows how it could be used to enforce the router flavor in `ingress` chart using subcharts values.

As I understand that would prevent using anything else but `expressions` with KIC >= 3.0 which might be too rigorous 🤔 

Sidenote: If I'm not mistaken, `.Subcharts` is an equivalent of getting these values from `.Values.controller` or `.Values.gateway`.

2023-11-09 13:52 UTC, pmalek commented
> As I understand that would prevent using anything else but `expressions` with KIC >= 3.0 which might be too rigorous 🤔

Hmm, yes. We'd like to set this for the user as in perform the defaulting in template code rather than limit the possibilities as https://github.com/Kong/charts/pull/937 is trying to do.

In this case I'm not sure this is possible this way (or at least without massive rewrite of `kong` chart into something like a gigantic template which would be rendered in `ingress` using provided subchart values 🤯 )

> Sidenote: If I'm not mistaken, `.Subcharts` is an equivalent of getting these values from `.Values.controller` or `.Values.gateway`.

`.Subcharts` is an object holding fields like `.Files`, `.Values` etc.

`.Subcharts.controller.Values` and `.Subcharts.gateway.Values` can be used in `ingress` chart to get values from subcharts.

2023-11-09 14:33 UTC, czeslavo commented
@pmalek I came up with another alternative: https://github.com/Kong/charts/pull/939. It sets the router flavor to expressions in `kong/ingress` and prevents using this kind of flavor with KIC < 3.0.

2025-02-03 12:36 UTC, pmalek commented
cc: @randmonkey 

In the effort of cleaning up the stale branches I'm closing this and removing the branch ( it's possible to recover that via "restore branch" button).

2025-02-03 12:36 UTC, closed without merging