feat: allow hostname override
Kong/charts pull request #943
Opened 2023-11-15 15:21 UTC by nicklasfrahm

#### What this PR does / why we need it:

Our API management uses Kong and we have dataplane deployments in multiple regions. At the moment our lovely uber-API guy REMOG creates a hardcopy of the helm chart, which drastically increases maintenance effort on his side.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] PR is based off the current tip of the `main` branch.
- [x] Changes are documented under the "Unreleased" header in CHANGELOG.md
- [x] New or modified sections of values.yaml are documented in the README.md
- [x] Commits follow the [Kong commit message guidelines](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#commit-message-format)

2023-11-15 15:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/charts?pullRequest=943) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/charts?pullRequest=943) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/charts?pullRequest=943) it.</sub>

2023-11-15 23:58 UTC, rainest requested changes
Suggested changed comments to refer to the upstream field, in a somewhat futile effort to explain how our values.yaml structure maps to underlying resources (we've been very bad about flattening different levels of resources).

Do you have more information about how this is actually used in hybrid installs in practice? It'd be better to explain that in detail under https://github.com/Kong/charts/blob/main/charts/kong/README.md#hybrid-mode. From the original comments it's not clear how the custom hostname would affect that or what values you should use for the control and data plane releases vis a vis their other settings.

Is there any reason to include `subdomain` along with this? https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields is a bit confusing as to the exact effects--I'm not sure if this has any effect on the cluster DNS entries or just the local hostname (and whether the former matters).

2023-11-15 23:58 UTC, rainest commented on charts/kong/README.md
> +| deployment.hostname                | Set a custom hostname. Very useful in controlplane/dataplane configurations.          |                     |
```suggestion
| deployment.hostname                | Set the Deployment's `.spec.template.hostname`        |                     |
```

2023-11-15 23:58 UTC, rainest commented on charts/kong/values.yaml
> +  # controlplane/dataplane setup with multiple dataplanes.
```suggestion
  # Set the Deployment's spec.template.hostname field.
```

2023-11-16 14:19 UTC, remogvestas commented
we use the hostname variable to have a saying hostname in the response of the  /clustering/data-planes endpoint, like:

data: [ [-]
     { [-]
       config_hash: b4d10b38ea9c510b0d5590c2c04a4fdb
       hostname: **dataplane-git-weu**
       id: 010be8cf-c5f9-42ea-b94f-76a3a05bda2c
       ip: xx.xx.xx.xx
       last_seen: 1700132083
       sync_status: normal
       ttl: 1209581
       version: 3.1.1.1
       
      so we easily can check the status of all dataplanes across all regions and instances

2023-11-16 18:49 UTC, rainest approved these changes

2023-11-16 18:51 UTC, merged